{% set name = "azure-purview-scanning" %}
{% set version = "1.0.0b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-purview-scanning-{{ version }}.zip
  sha256: 82d9cccd9e3ddc93a7c4fe3353cc5dc359beae7596aea75ca959fe69f8dc9171

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - azure-core <2.0.0,>=1.18.0
    - msrest >=0.6.21
    - six >=1.11.0
    - typing

test:
  imports:
    - azure.purview.scanning
    - azure.purview.scanning.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Purview Scanning Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - redur
